/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package technical.test.ekwateur;

import java.util.List;

import technical.test.ekwateur.entity.Client;
import technical.test.ekwateur.entity.ClientPro;
import technical.test.ekwateur.entity.EnergyConsumption;
import technical.test.ekwateur.entity.EnergyType;
import technical.test.ekwateur.service.InvoiceService;
import technical.test.ekwateur.service.impl.InvoiceConsoleServiceImpl;

public class App {
    public static void main(String[] args) {

        Client client = new ClientPro("EKW00000001", "E12311331", "Bring Company", 10031990);

        EnergyConsumption electricityConsumption = new EnergyConsumption(EnergyType.ELECTRICITY, 290);
        EnergyConsumption gazConsumption = new EnergyConsumption(EnergyType.GAZ, 85);

        InvoiceService invoiceService = new InvoiceConsoleServiceImpl();
        invoiceService.sendInvoice(client, List.of(electricityConsumption, gazConsumption));

    }
}
